name: Deploy to GitHub Pages

on:
  schedule:
    - cron: "*/5 * * * *"  # run every 5 minutes
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Generate static site
        run: python build_news.py
        env:
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}

      - name: List generated site folder contents
        run: ls -la site/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          publish_branch: gh-pages

      - name: Install dependencies for lxml html clean
        run: pip install lxml[html_clean] lxml_html_clean

